# Generated by Django 2.2.28 on 2023-02-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
