# Generated by Django 2.2.28 on 2023-02-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230228_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dateOfBirth',
        ),
    ]
