# Generated by Django 4.1.7 on 2023-03-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
