# Generated by Django 4.1.7 on 2023-03-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userwishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWishList',
        ),
    ]
