# Generated by Django 2.1.5 on 2023-03-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('unique_car_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('ford', 'Ford'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('mercedes_benz', 'Mercedes-Benz'), ('nissan', 'Nissan'), ('porsche', 'Porsche'), ('tesla', 'Tesla'), ('toyota', 'Toyota')], max_length=14)),
                ('model', models.CharField(max_length=18)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=4)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='car_images/')),
                ('num_of_seats', models.PositiveIntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (7, '7'), (8, '8')])),
                ('body_type', models.CharField(choices=[('saloon', 'Saloon'), ('estate', 'Estate'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('convertible', 'Convertible')], max_length=11)),
                ('mileage', models.PositiveIntegerField()),
                ('gearbox', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=9)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric')], max_length=8)),
                ('year_of_manufacture', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4)),
                ('colour', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=6)),
                ('location', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
