# Generated by Django 4.1.7 on 2023-03-21 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cars.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_remove_car_gearbox_remove_car_year_of_manufacture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('saloon', 'Saloon'), ('estate', 'Estate'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('convertible', 'Convertible')], max_length=11, null=True, verbose_name='Body type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('ford', 'Ford'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('mercedes_benz', 'Mercedes-Benz'), ('nissan', 'Nissan'), ('porsche', 'Porsche'), ('tesla', 'Tesla'), ('toyota', 'Toyota')], max_length=14, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=6, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=4, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric')], max_length=8, null=True, verbose_name='Fuel type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, choices=[('london', 'London'), ('birmingham', 'Birmingham'), ('manchester', 'Manchester'), ('leeds', 'Leeds'), ('liverpool', 'Liverpool'), ('glasgow', 'Glasgow'), ('edinburgh', 'Edinburgh'), ('aberdeen', 'Aberdeen')], max_length=10, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, choices=[('a3', 'A3'), ('a4_avant', 'A4 Avant'), ('q7', 'Q7'), ('a6', 'A6'), ('a5', 'A5'), ('e_tron', 'E-tron'), ('1_series', '1 Series'), ('3_series', '3 Series'), ('4_series', '4 Series'), ('5_series', '5 Series'), ('x5', 'X5'), ('ix3', 'IX3'), ('focus', 'Focus'), ('puma', 'Puma'), ('monedo', 'Monedo'), ('mustang', 'Mustang'), ('xf', 'Xf'), ('a3', 'A3'), ('f_pace', 'F-pace'), ('e_pace', 'I-pace'), ('xe', 'XE'), ('f_type', 'F-type'), ('range_rover_evoque', 'Range Rover Evoque'), ('range_rover_velar', 'Range Rover Velar'), ('range_rover', 'Range Rover'), ('discovery', 'Discovery'), ('a_class', 'a Class'), ('c_class', 'c Class'), ('e_class', 'e Class'), ('g_class', 'G Class'), ('eqa', 'EQA'), ('eqs', 'EQS'), ('micra', 'Micra'), ('leaf', 'Leaf'), ('gtr', 'GT-R'), ('juke', 'Juke'), ('qashqai', 'Qashqai'), ('taycan', 'Taycan'), ('panamera', 'Panamera'), ('macan', 'Macan'), ('cayman', 'Cayman'), ('boxter', 'Boxter'), ('model_3', 'Model 3'), ('model_x', 'Model X'), ('model_y', 'Model Y'), ('model_s', 'Model S'), ('yaris', 'Yaris'), ('corolla', 'Corolla'), ('chr', 'CH-R'), ('camry', 'Camry'), ('supra', 'Supra'), ('a3', 'A3')], max_length=18, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='num_of_seats',
            field=models.PositiveIntegerField(blank=True, choices=[(2, '2'), (4, '4'), (5, '5'), (7, '7'), (8, '8')], null=True, verbose_name='Number of seats'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[cars.validators.is_positive], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=9, null=True, verbose_name='Transmission'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[cars.validators.is_valid_year], verbose_name='Year'),
        ),
    ]
