# Generated by Django 4.1.7 on 2023-03-22 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0002_remove_car_gearbox_remove_car_year_of_manufacture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
