# Generated by Django 4.1.7 on 2023-03-23 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_alter_car_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='Wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Wishlist'),
        ),
    ]
